version: "3.9"

services:
  backend:
    build: ./backend
    container_name: express-backend
    ports:
      - "10001:10001"
    env_file:
      - .env
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://localhost:10001
    container_name: vite-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  redis:
    image: redis:7
    container_name: redis-cache
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
